- src/main/java/ch/heigvd/res/chill/domain/vkaelin/Jorat.java
- src/test/java/ch/heigvd/res/chill/domain/vkaelin/JoratTest.java
Adds the beer "La blanche du Jorat". Closes #80
> Add Jorat beer

- src/main/java/ch/heigvd/res/chill/domain/HUART1848/Amogus.java
- src/test/java/ch/heigvd/res/chill/domain/HUART1848/AmogusTest.java
> Add Amogus beer

- src/main/java/ch/heigvd/res/chill/domain/vogelma/Sinalco.java
- src/test/java/ch/heigvd/res/chill/domain/vogelma/SinalcoTest.java
> Add some refresh Sinalco with test

- src/main/java/ch/heigvd/res/chill/domain/lollipoke/Cardinal.java
- src/test/java/ch/heigvd/res/chill/domain/lollipoke/CardinalTest.java
> Add Cardinal with tests

- src/main/java/ch/heigvd/res/chill/domain/MrDaves24/Anker.java
- src/test/java/ch/heigvd/res/chill/domain/MrDaves24/AnkerTest.java
> Implement Anker

- src/main/java/ch/heigvd/res/chill/domain/MbayoG/Kwak.java
- src/test/java/ch/heigvd/res/chill/domain/MbayoG/KwakTest.java
> Add Kwak with test

- src/main/java/ch/heigvd/res/chill/domain/MehSalhi/Pecheresse.java
- src/test/java/ch/heigvd/res/chill/domain/MehSalhi/PecheresseTest.java
Please have a look at my PR. Should close #23 .
> Add Pecheresse with unit tests

- src/main/java/ch/heigvd/res/chill/domain/wasadigi/PrixGaranti.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/PrixGarantiTest.java
> Added PG and tests

- src/main/java/ch/heigvd/res/chill/domain/jorisSchaller/Kekette.java
- src/test/java/ch/heigvd/res/chill/domain/jorisSchaller/KeketteTest.java
> implemented Kekette

- src/main/java/ch/heigvd/res/chill/domain/MasterZeus97/Cidre.java
- src/test/java/ch/heigvd/res/chill/domain/MasterZeus97/CidreTest.java
> Add Cidre with tests

- src/main/java/ch/heigvd/res/chill/domain/hadrylouis/ClubMate.java
- src/test/java/ch/heigvd/res/chill/domain/hadrylouis/ClubMateTest.java
> Add Club-Mate with tests

- src/main/java/ch/heigvd/res/chill/domain/NicolasWichoud/Chouffe.java
- src/test/java/ch/heigvd/res/chill/domain/NicolasWichoud/ChouffeTest.java
> Add Chouffe with test

- src/main/java/ch/heigvd/res/chill/domain/b0ogieMan/Tenebreuse.java
- src/test/java/ch/heigvd/res/chill/domain/b0ogieMan/TenebreuseTest.java
> Add Tenebreuse with tests

- src/main/java/ch/heigvd/res/chill/domain/AlenBijelic99/Strongbow.java
- src/test/java/ch/heigvd/res/chill/domain/AlenBijelic99/StrongbowTest.java
> Add strongbow with tests

- src/main/java/ch/heigvd/res/chill/domain/luhrel/Sapin.java
- src/test/java/ch/heigvd/res/chill/domain/luhrel/SapinTest.java
Resolve https://github.com/HEIGVD-Course-API/API-2021-Chill/issues/67
> Add Sapin beer

- src/main/java/ch/heigvd/res/chill/domain/AJaquier/PrixGarantie.java
- src/test/java/ch/heigvd/res/chill/domain/AJaquier/PrixGarantieTest.java
> Add Prix garantie with tests

- src/main/java/ch/heigvd/res/chill/domain/painda/Bulmers.java
- src/test/java/ch/heigvd/res/chill/domain/painda/BulmersTest.java
> Add bulmers with tests

- src/main/java/ch/heigvd/res/chill/domain/BasileCuneo/StFeuillien.java
- src/test/java/ch/heigvd/res/chill/domain/BasileCuneo/StFeuillienTest.java
> added StFeuillien beer

- src/main/java/ch/heigvd/res/chill/domain/Lazzzer/Budweiser.java
- src/test/java/ch/heigvd/res/chill/domain/Lazzzer/BudweiserTest.java
> Add Budweiser

- src/main/java/ch/heigvd/res/chill/domain/LucaCoduriV/CuveeDesTrolls.java
- src/test/java/ch/heigvd/res/chill/domain/LucaCoduriV/CuveeDesTrollsTest.java
> Added cuvee trolls

- src/main/java/ch/heigvd/res/chill/domain/BernardLhermite/GuldenDraak.java
- src/test/java/ch/heigvd/res/chill/domain/BernardLhermite/GuldenDraakTest.java
> Add Gulden Draak with tests

- src/main/java/ch/heigvd/res/chill/domain/theomi/Leffe.java
- src/test/java/ch/heigvd/res/chill/domain/theomi/LeffeTest.java
> Added Leffe with tests

- src/main/java/ch/heigvd/res/chill/domain/GeraudSilvestri/Eve.java
- src/test/java/GeraudSilvestri/EveTest.java
> Add Eve with test

- src/main/java/ch/heigvd/res/chill/domain/NelsonJnrnd/GingerBeer.java
- src/test/java/ch/heigvd/res/chill/domain/NelsonJnrnd/GingerBeerTest.java
> Add Ginger Beer with tests

- src/main/java/ch/heigvd/res/chill/domain/justinrausis/Blonde25.java
- src/test/java/ch/heigvd/res/chill/domain/justinrausis/Blonde25Test.java
> add Blonde25 with test

- src/main/java/ch/heigvd/res/chill/domain/BernardLhermite/Gralsburg.java
- src/test/java/ch/heigvd/res/chill/domain/BernardLhermite/GralsburgTest.java
> Add Gralsburg with tests

- src/main/java/ch/heigvd/res/chill/domain/GeraudSilvestri/Maccabi.java
- src/test/java/ch/heigvd/res/chill/domain/GeraudSilvestri/MaccabiTest.java
> Add maccabi with tests

- src/main/java/ch/heigvd/res/chill/domain/NunezTania/Cusquena.java
- src/test/java/ch/heigvd/res/chill/domain/NunezTania/CusquenaTest.java
> Adding Cusquena

- src/main/java/ch/heigvd/res/chill/domain/Marinlestylo/Maximator.java
- src/test/java/ch/heigvd/res/chill/domain/Marinlestylo/MaximatorTest.java
> Add Maximator with tests

- .gitignore
- src/main/java/ch/heigvd/res/chill/domain/HUART1848/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/HUART1848/GuinnessTest.java
> Add Guinness

- src/main/java/ch/heigvd/res/chill/domain/BernardLhermite/Huithuit.java
- src/test/java/ch/heigvd/res/chill/domain/BernardLhermite/HuithuitTest.java
> Add Huithuit with tests

- src/main/java/ch/heigvd/res/chill/domain/IvanR_Vecerina/DrGabsIPA.java
- src/test/java/ch/heigvd/res/chill/domain/IvanR_Vecerina/DrGabsIPATest.java
> Add Dr.Gabs IPA with tests

- src/main/java/ch/heigvd/res/chill/domain/GeraudSilvestri/Efes.java
- src/test/java/ch/heigvd/res/chill/domain/GeraudSilvestri/EfesTest.java
> Add efes with tests

- src/main/java/ch/heigvd/res/chill/domain/chloefont/Swaf.java
- src/test/java/ch/heigvd/res/chill/domain/chloefont/SwafTest.java
> Add Swaf with tests

- src/main/java/ch/heigvd/res/chill/domain/AJaquier/Pisswasser.java
- src/test/java/ch/heigvd/res/chill/domain/AJaquier/PisswasserTest.java
Second version of #100. Hope it's ok
> Add Pisswasser with tests

- src/main/java/ch/heigvd/res/chill/domain/VincentPeer/Vinyldeco.java
- src/test/java/ch/heigvd/res/chill/domain/VincentPeer/VinyldecoTest.java
> Add Vinyldeco

- src/main/java/ch/heigvd/res/chill/domain/theomi/Tsingtao.java
- src/test/java/ch/heigvd/res/chill/domain/theomi/TsingtaoTest.java
> added tsingtao

- src/main/java/ch/heigvd/res/chill/domain/chloefont/Ichnusa.java
- src/test/java/ch/heigvd/res/chill/domain/chloefont/IchnusaTest.java
> Add Ichnusa and tests

- src/main/java/ch/heigvd/res/chill/domain/BenVal555/Tell.java
- src/test/java/ch/heigvd/res/chill/domain/BenVal555/TellTest.java
> Added Tell class + tests

- src/main/java/ch/heigvd/res/chill/domain/damianomondaini/ThomasMueller.java
- src/test/java/ch/heigvd/res/chill/domain/damianomondaini/ThomasMuellerTest.java
> Added Thomas Mueller

- src/main/java/ch/heigvd/res/chill/domain/Marinlestylo/PipouBeer.java
- src/test/java/ch/heigvd/res/chill/domain/Marinlestylo/PipouBeerTest.java
> Add PipouBeer with tests with only the right files

- src/main/java/ch/heigvd/res/chill/domain/NicolasWichoud/Rivella.java
- src/test/java/ch/heigvd/res/chill/domain/NicolasWichoud/RivellaTest.java
> add Rivella

- src/main/java/ch/heigvd/res/chill/domain/NicolasWichoud/Calanda.java
- src/test/java/ch/heigvd/res/chill/domain/NicolasWichoud/CalandaTest.java
> add Calanda with test

- src/main/java/ch/heigvd/res/chill/domain/dylanrodr_heig/Hope.java
- src/test/java/ch/heigvd/res/chill/domain/dylanrodr_heig/HopeTest.java
> Add Hope with tests

- src/main/java/ch/heigvd/res/chill/domain/jupct/Monaco.java
- src/test/java/ch/heigvd/res/chill/domain/jupct/MonacoTest.java
> Add Mojito with tests

- src/main/java/ch/heigvd/res/chill/domain/heryck237/Origin.java
- src/test/java/ch/heigvd/res/chill/domain/heryck237/OriginTest.java
> Adding origin beer with tests

- src/main/java/ch/heigvd/res/chill/domain/jupct/Flamingo.java
- src/test/java/ch/heigvd/res/chill/domain/jupct/FlamingoTest.java
> Add flamingo with tests

- src/main/java/ch/heigvd/res/chill/domain/lollipoke/CardinalBlanche.java
- src/test/java/ch/heigvd/res/chill/domain/lollipoke/CardinalBlancheTest.java
> Add Cardinal blanche with test

- src/main/java/ch/heigvd/res/chill/domain/BenVal555/Amsterdam.java
- src/test/java/ch/heigvd/res/chill/domain/BenVal555/AmsterdamTest.java
> Added Amsterdam bier + tests

- src/main/java/ch/heigvd/res/chill/domain/MehSalhi/Kriek.java
- src/test/java/ch/heigvd/res/chill/domain/MehSalhi/KriekTest.java
I added the beer Kriek. Should close #179
> Added Kriek and unit tests

- src/main/java/ch/heigvd/res/chill/domain/clemdiep/Chouffe.java
- src/test/java/ch/heigvd/res/chill/domain/clemdiep/ChouffeTest.java
> Add Chouffe beer and test

- src/main/java/ch/heigvd/res/chill/domain/luhrel/LaBlonde.java
- src/test/java/ch/heigvd/res/chill/domain/luhrel/LaBlondeTest.java
Fix https://github.com/HEIGVD-Course-API/API-2021-Chill/issues/190
> Add "La Blonde" beer

- src/main/java/ch/heigvd/res/chill/domain/Isotech42/Water.java
- src/test/java/ch/heigvd/res/chill/domain/Isotech42/WaterTest.java
> Add Water with tests

- src/main/java/ch/heigvd/res/chill/domain/pain_da/Bulmers.java
- src/test/java/ch/heigvd/res/chill/domain/pain_da/BulmersTest.java
changed painda repository to pain_da
> Changed repository name

- src/main/java/ch/heigvd/res/chill/domain/MbayoG/Kriek.java
- src/test/java/ch/heigvd/res/chill/domain/MbayoG/KriekTest.java
> add kriek and test

- src/main/java/ch/heigvd/res/chill/domain/MaximGY/IceTea.java
- src/test/java/ch/heigvd/res/chill/domain/MaximGY/IceTeaTest.java
> Implemented IceTea & tests

- src/main/java/ch/heigvd/res/chill/domain/vogelma/TheFroid.java
- src/test/java/ch/heigvd/res/chill/domain/vogelma/TheFroidTest.java
> add some refreshing ice tea with tests

- src/main/java/ch/heigvd/res/chill/domain/JBAHEIG/BlueMoon.java
- src/test/java/ch/heigvd/res/chill/domain/JBAHEIG/BlueMoonTest.java
> Added BlueMoon correctly

- src/main/java/ch/heigvd/api/chill/domain/nigelmann/Kumis.java
- src/test/java/ch/heigvd/api/chill/domain/nigelmann/KumisTest.java
> [TASK] Add kumis

- src/main/java/ch/heigvd/api/chill/domain/nigelmann/CoffeeGoutte.java
- src/test/java/ch/heigvd/api/chill/domain/nigelmann/CoffeGoutteTest.java
> [TASK] add some coffee with booze, let's get loaded for bears

- src/main/java/ch/heigvd/api/chill/domain/noahboegli/RedBull.java
- src/test/java/ch/heigvd/api/chill/domain/noahboegli/RedBullTest.java
Enjoy caffeine and energy !
Closes #254
> [TASK] Added RedBull

- src/main/java/ch/heigvd/api/chill/domain/noahboegli/ScottishWhiskey.java
- src/test/java/ch/heigvd/api/chill/domain/noahboegli/ScottishWhiskeyTest.java
> [TASK] Added scottish whiskey

- src/main/java/ch/heigvd/api/chill/domain/hugomendes98/IceTeaOolong.java
- src/test/java/ch/heigvd/api/chill/domain/hugomendes98/IceTeaOolongTest.java
Ooling Ice Tea.
(FYI, I search and this flavor exists)
> Ice Tea (oolong) added

- src/main/java/ch/heigvd/api/chill/domain/hugomendes98/IceTeaLemon.java
- src/test/java/ch/heigvd/api/chill/domain/hugomendes98/IceTeaLemonTest.java
> Hm icetealemon

- src/main/java/ch/heigvd/api/chill/domain/fterrani/WhiteRussian.java
- src/test/java/ch/heigvd/api/chill/domain/fterrani/WhiteRussianTest.java
> White russian... finally!

- src/main/java/ch/heigvd/api/chill/domain/noahboegli/Rhum.java
- src/test/java/ch/heigvd/api/chill/domain/noahboegli/RhumTest.java
Closes #235 
Enjoy the rhum guys !
> [TASK] Implemented rhum drink

- src/main/java/ch/heigvd/api/chill/domain/yanickheig/Kwak.java
- src/test/java/ch/heigvd/api/chill/domain/yanickheig/KwakTest.java
> added kwak

- src/main/java/ch/heigvd/api/chill/domain/ouupps/Vedette.java
- src/test/java/ch/heigvd/api/chill/domain/ouupps/VedetteTest.java
> Add beer Vedette

- src/main/java/ch/heigvd/api/chill/domain/heigvdgachetje/LongIslandIcedTea.java
- src/test/java/ch/heigvd/api/chill/domain/heigvdgachetje/LongIslandIcedTeaTest.java
> Add Long Island Iced Tea with tests

- src/main/java/ch/heigvd/api/chill/domain/hugomendes98/IceTeaPeach.java
- src/test/java/ch/heigvd/api/chill/domain/hugomendes98/IceTeaPeachTest.java
Ice Tea, flavor peach, has been added
> Ice Tea (peach) added

- src/main/java/ch/heigvd/api/chill/domain/ouupps/Guinness.java
- src/test/java/ch/heigvd/api/chill/domain/ouupps/GuinnessTest.java
> Add Guinness beer

- src/main/java/ch/heigvd/api/chill/domain/fterrani/Vesper.java
- src/test/java/ch/heigvd/api/chill/domain/fterrani/VesperTest.java
> Added Vesper cocktail

- src/main/java/ch/heigvd/api/chill/domain/heigvdgachetje/GinTonic.java
- src/test/java/ch/heigvd/api/chill/domain/heigvdgachetje/GinTonicTest.java
> Add gin tonic with tests

- src/main/java/ch/heigvd/api/chill/domain/yanickheig/Pecheresse.java
- src/test/java/ch/heigvd/api/chill/domain/yanickheig/PecheresseTest.java
> Added pecheresse
